### ISSUE TITLE
Request to include Chi2 and number of clusters (hits) used in the fit

### ISSUE THREAD

**Issue by Simple-Shyam** [eic/EDM4eic#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I am understanding the performance of fitter in ACTS, therefore, I need Chi2 and number of hits used in the fit in the output tree to get the more understanding about the fitter.
m_log->debug("   chi2 = {}", trajState.chi2Sum);
**Describe alternatives you've considered**

**Additional context**

**Comment by wdconinc** [comment]
chi2 and number of hits is avialable in the Track data type of the EDM4hep data model, https://github.com/key4hep/EDM4hep/blob/v00-06/edm4hep.yaml#L355.
