### ISSUE TITLE
Refactor data model to better fit JANA workflow

### ISSUE THREAD

**Issue by faustus123** [eic/EDM4eic#2]
One of the main differences in the paradigms between JANA and the existing Gaudi-informed data model is what they use as the primary key for connecting data and algorithms. Specifically, podio uses collection names (a string) as the primary key and emphasizes a small set of common data types. One may ask for a collection by name and then discover the type. JANA is designed around using typeid as the primary key and a factory tag (a string) as a secondary key (which is only needed for special cases).

The existing data model was designed with a Gaudi-like system in mind. For example, the _edm4hep::SimCalorimeterHit_ is made to serve both the E/M barrel and Hardronic Endcap calorimeters. In order to use this data model in a JANA-like system, we must basically sacrifice the secondary key to use as the primary key. However, if the data model were extended to include both _EEMCSimCalorimeterHit_ and _HCALSimCalorimeterHit_ types (both inheriting from _edm4hep::SimCalorimeterHit_) then these could serve as primary keys in JANA. This would also result in a more complete data model. As it is, the data model does not contain any information about  _EEMC_ or _HCAL_. While the fields are the same, the nature of those is quite different.

Using a data model designed with a different framework in mind than the one it is being used with can lead to awkward code patterns as it is doing with JANA. This change should be relatively easy as it does not modify existing data types, only adds new, trivial ones. Another added benefit will be that if the EEMC decides it needs an additional field, we will already have a dedicated type to insert this change into without having to modify the _edm4hep::SimCalorimeterHit_ base class.

One side effect of this will be that generic algorithms will be harder to implement. The inputs will not be an issue since upcasting to a core edm4hep type is trivial. The outputs though will present a different challenge since the algorithm itself will need to instantiate objects of the derived type. (e.g. it should produce objects of type _EEMCSimCalorimeterHit_ when run for that detector but type _HCALSimCalorimeterHit_ when producing objects for that detector.) This is one of multiple challenges though with the generic algorithms already. A major one being that Gaudi/podio works with _Collection_s of objects while JANA deals with vectors of _const pointers_. If we made all generic algorithms work with std::vectors of pointers, JANA would be happier, but Gaudi would not. Same is true the other way around. (Yes, we can force it one way or the other, but this will be the tail wagging the dog.)

**Comment by sly2j** [comment]
Here are my immediate thoughts on your proposal:

I am quite strongly opposed against making this change at the data model level. It entangles all of the parts of our software chain with each other where they are currently nicely independent. It would effectively break one of the core design principles behind the data model, and even break how we do the detector readout in DD4hep (this is where the SimCalorimeterHit or the SimTrackerHit come from). Entangling everything together (how many different types of TrackerHits would you need here?) would also violates our Statement of Principles in multiple places. Do we really now need a different data model for each of the detector versions that we will need to simulate during the optimization phase? Or when picking detector technologies.

The flexibility we get through the modularity is why we picked the data model in the first place. The data model is designed to be used for modern data-driven functional algorithms. This works with Gaudi, but it also works with a lot of other frameworks (even ROOT's RDataFrame). I don't see why this has to be a problem for JANA2. Is the only problem that every structure has to be a unique type? 

Couldn't an alternative solution be something like either
```cpp
template <struct Type, struct Tag> struct DataWrapper : Type { using data_tag = Tag; };
struct EEMC_tag;
using EEMCSimCalorimeterHit = DataWrapper<SimCalorimeterHit, EEMC_tag>;
```

This solution could also have some other advantages as we can mark all EEMC-related structures with the same tag.

Or we could just use direct inheritance
```cpp
struct EEMCSimCalorimeterHit : SimCalorimeterHit {};
```

I feel that we can come to an architecturally sound solution that does not suddenly get rid of all of the modularity we have in our ecosystem.

**Comment by faustus123** [comment]
I chose a poor example. I should not have pointed to the SimCalorimeterHit but instead to something like RawCalorimeterHit. The proposal would not change anything in the simulation output. It would just add classes that the algorithms in the reconstruction would produce. Your examples are pretty much right on the nose. The point is that putting those types of inherited classes in the EICrecon code achieves exactly the same result as having the data model generate those lines. The goal is to have those types defined with the rest of the data model.

I'm not sure if I quite see the point on it violating the Statement of Principles, but maybe I'm missing something.

**Comment by faustus123** [comment]
One other small point: Your second example is the first thing we did. The hidden issue there is with constructor arguments. You can get around it with variadic templates, but it is a bit ugly and leads to slightly more confusing errors. It is much cleaner to have the data model generate the constructors in the same way it does for the core classes.

**Comment by sly2j** [comment]
I think the following solution (see below) may solve this issue without having to change the data model directly. I included 2 strategies, one where we avoid explicitly using the Wrapper, bypassing the issue of exposing data members, and then one where we use the Wrapper directly and then access the data members. The latter needs a variadic template, the former does not. Added advantage of this solution is that it directly allows us to write generic algorithms and still have them access the correct data types.

```cpp
template <class RawData, class Tag> struct DataWrapper : RawData {
  using tag = Tag;
  // The variadic template is only needed when using the pattern (2) below
  template <class... Args> DataWrapper(Args... args) : RawData(args...) {}
  // Make sure DataWrapper plays nice with RawData
  DataWrapper(const RawData& rd) : RawData(rd) {}
  DataWrapper(RawData&& rd) : RawData(std::move(rd)) {}
  DataWrapper& operator=(const RawData& rd) { DataWrapper::operator=(rd); return *this;}
  DataWrapper& operator=(RawData&& rd) { DataWrapper::operator=(std::move(rd)); return *this;}
  // Data access to the underlying types only needed for solution (2) below
  RawData& data() { return static_cast<RawData&>(*this); }
  const RawData& data() const { return static_cast<const RawData&>(*this); }
};

template <class Tag>
class CalorimeterClusterAlgorithm {
  using HitType = DataWrapper<edm4hep::CalorimeterHit, Tag>;
  using ClusterType = DataWrapper<edm4hep::Cluster, Tag>;

  // this is the higher level process "boilerplate" that gets the data and then calls the
  // actual algorithm
  int process() {
    // Data persistency magic
    const std::vector<const HitType*> input_hits = ... ;
    std::vector<const ClusterType*> output_clustes = ... ;
    // Two ways of interacting
    // 1. Just use the underlying types for the read-only classes, and avoid
    //    using the wrapper types altogether except at the boundary with the data store
    //    (implicitly cast to pointers to the base type)
    for (const edm4hep::CalorimeterHit* hit : input_hits) {
      std::cout << hit->getPosition().x << std::endl;
      // do stuff
      edm4hep::Cluster tmp_cluster {E, x, y, z};
      output_clusters.push_back(allocate_cluster(new_cluster));
    }
    // 2. Or use the wrapped types directly, at the cost of needing a variadic template in
    // the DataWrapper, and for using extra ->data() calls
    for (const edm4hep::CalorimeterHit* hit : input_hits) {
      std::cout << hit->data().getPosition().x << std::endl;
      // do stuff
      edm4hep::Cluster* new_cluster = allocate_cluster(E, x, y, z);
      output_clusters.push_back(new_cluster)
    }
  }
};


struct BEMC_tag {};
using BEMCCalorimeterHit = DataWrapper<edm4hep::CalorimeterHit, BEMC_tag>;
using BEMCClusterAlgo = CalorimeterClusterAlgorithm<BEMC_tag>
```

**Comment by faustus123** [comment]
So, I'm not seeing where "allocate_cluster" is defined (?) is that supposed to just be "new ClusterType(E,x,y,z)" ? That would make sense.

If I understand this example, we would be creating new data types that effectively tie the collection name to the edm4hep (or edm4eic) data type. This also would make the generic algorithm object a templated class. I guess that would mean there should be a default type for "Tag" for anyone using the algorithm where they do not need/want this tag. 

This is clever. Parts of it look similar to some strategies we have already tried. For example, we tried having the input/output data types come into the algorithm directly as template parameters: e.g. 

~~~
template<typename HitType = edm4hep::CalorimeterHit , typename ClusterType = edm4hep::Cluster> ) Then we could use classes defined as in your previous post. Using direct template arguments eliminates the need of having the wrapper class. The benefit of your DataWrapper though would be that it is defined in one place whereas with "EEMCSimCalorimeterHit" every derived type would need to fill in at least the variadic template constructor for each of those class definitions. (Hence, asking why not have podio do this for us without needing variadic templates?)

We ended up rejecting the templated algorithm classes because it pushes all of the algorithm code into a template. This can blow up the binaries and cause more confusing errors which I assumed would get negative blowback from the users. One may ague they would be more accepting. (I don't really know.)

So I think the main thing I would like to understand is why adding some inherited types to edm4eic is so problematic. (I'm honestly asking since I don't quite know). All of these inherited types could be upcast into core types for writing so I don't think this should change anything in the files (either input or output).

**Comment by wdconinc** [comment]
> Another added benefit will be that if the EEMC decides it needs an additional field, we will already have a dedicated type to insert this change into without having to modify the edm4hep::SimCalorimeterHit base class.

This is exactly the reason we don't want to do this. The benefit of a data model is that it allows generic algorithms on a common data description of the underlying detectors.

**Comment by sly2j** [comment]
* `alocate_cluster` is essentially meant to be `operator new`, but with provisions that there may be framework dependent magic happening here.
* I agree that a default type for `Tag` would be good practice here. Maybe something that works (in this example) with a generic calorimeter implementation assuming some naming convention.
* I think the DataWrapper-like approach leads to less code duplication which is typically preferable.
* I don't think we need to be scared of templates at this level, as the approach is relatively simple. Down the road we could even think of using Concepts to maximize the user-friendliness. But I would argue in this case most of the work depends on the skeleton builder and documentation side (just as in any other approach). I don't think the binary size would be affect in this particular case compared to the cases you propose. That also smells a bit like premature optimization - we can always factorize out the majority of an algorithm's body if that is really an issue.
* The data model should not cary information about the framework-specific use of the data model. It defines the API for accessing our data in a way that does not tie us to one particular technology at each and every step of the reconstruction-digitization-reconstruction toolchain. Changing this because of internal architectural reasons breaks with this, and introduces complexity/granularity where it isn't needed. Suddenly you throw any kind of common software development with adjacent experiments out of the window. And I don't think in this case there is a technological reason to do so. If I understand everything correctly, JANA2 uses the C++ type system for addressing just like Gaudi uses string lookups for addressing. That is fine and has nothing to do with the data model. It is in my opinion just wrong to then introduce unneeded inheritance chains in the data model (which has in principle nothing to do even with C++). If we need inheritance to be able to marry the data model with the memory model in JANA2, we should do it in as light-handed of a way. I would argue my approach accomplishes this. You could also introduce code generation into JANA2 directly to accomplish this (effectively extending EDM4hep just for the reconstruction), but in my opinion directly using C++ language features fits much better with the rest of the design of JANA2. You mentioned multiple times during the Gaudi vs JANA2 discussion that you prefer using C++ language features over using a mixed approach to accommodate Python at every level. Well, I would argue this is one of the places where there is a clean pure C++ approach to do this with very minimal additional maintenance burden.
