### ISSUE TITLE
Add surface ID member to edm4eic::TrackPoint

### ISSUE THREAD

**Issue by tylerkutz** [eic/EDM4eic#39]
For the purposes of track projections, it would be useful to add a member to TrackPoint that could be used to store the name/ID of the detector/surface the track was projected to.

The simplest solution would be an integer member that could store the detector ID as defined in https://github.com/eic/epic/blob/main/compact/definitions.xml.

**Comment by veprbl** [comment]
cc @c-dilks regarding the projection business

**Comment by wdconinc** [comment]
Likely you want the acts surface id, right?

**Comment by tylerkutz** [comment]
Following [this discussion on Mattermost](https://chat.epic-eic.org/main/pl/hwqi964jjpd4xkyyxijrk4jose), it was my plan to populate this field with the detector IDs defined [here](https://github.com/eic/epic/blob/main/compact/definitions.xml).

However, I am having issues with the implementation (see [new EICrecon branch](https://github.com/eic/EICrecon/tree/480-writing-out-track-propagation-information) and [explanation of the problem](https://chat.epic-eic.org/main/pl/qsa4ya8qdpb35cztq6z6csqu1y))

**Comment by c-dilks** [comment]
> cc @c-dilks regarding the projection business

I'm not sure how we can take advantage of this feature for our particular use cases in the RICHes, but good to keep in mind in case we ever need this. CC @chchatte92 @alexander-kiselev @kkauder
